<?php

$struct = array("Event Name","Start Date","Start Time","End Date","End Time","Location","Org Name","Image","Description");
$events = array(
array("Man of Steel", "Thu Sep 12, 2013", "7:00 PM", "Thu Sep 12, 2013", "10:00 PM", "Rudder Theatre", "MSC Aggie Cinema", "Man of Steel 2.jpg", "A showing of the summer Blockbuster Man of Steel not starring Christopher Reeve who was the 2nd original Superman"),
array("Speed Bump: Dave Coverly", "Tue Oct 29, 2013", "", "Fri Jan 10, 2014", "", "Visual Arts Gallery (MSC 2421)", "MSC Visual Arts Committee", "coverly_delivery.jpg", "MSC Visual Arts Committee presents the comic world of Dave Coverly, syndicated cartoon artist and illustrator of the funnies favorite, Speed Bump. This exhibition will feature original panels from Coverly's colorful cartoon and text panels detailing Coverly's creative process. Enjoy this light-hearted break from academia."),
array("Speed Bump: Dave Coverly Opening Reception", "Thu Nov 7, 2013", "6:30 PM", "Thu Nov 7, 2013", "8:30 PM", "Visual Arts Gallery (MSC 2421)", "MSC Visual Arts Committee", "coverly_delivery.jpg", "MSC Visual Arts Committee presents the comic world of Dave Coverly, syndicated cartoon artist and illustrator of the funnies favorite, Speed Bump. This exhibition will feature original panels from Coverly's colorful cartoon and text panels detailing Coverly's creative process. Enjoy this light-hearted break from academia."),
array("Lunchbox Concert with Walker Lukens", "Thu Nov 21, 2013", "12:00 PM", "Thu Nov 21, 2013", "1:00 PM", "Rudder Fountain", "MSC Town Hall", "lukens_web.jpg", "Join us for MSC Town Hall Lunchbox Concert Series Presents Walker Lukens at Rudder Fountain from noon to one on November 21st."),
array("MICHAEL MARTIN MURPHEY'S COWBOY CHRISTMAS CONCERT", "Tue Dec 3, 2013", "7:30 PM", "Tue Dec 3, 2013", "", "Rudder Auditorium", "MSC OPAS", "m3350.jpg", "Dust off your boots and grab your Stetson because multiple Grammy® Award nominee Michael Martin Murphey is coming to town to spread yuletide cheer in his family-friendly concert filled with cowboy songs and poetry. Sponsored by Spirit of Texas Bank."),
array("JUNIE B. IN JINGLE BELLS, BATMAN SMELLS", "Sun Dec 8, 2013", "2:00 PM", "Sun Dec 8, 2013", "", "Rudder Theatre", "MSC OPAS", "junie_b350.jpg", "It's holiday time, and everyone's favorite first grader is back to celebrate! All of the students in Room One are happily creating the perfect holiday party. Except how is Junie B. supposed to enjoy anything when she has drawn the name of her arch nemesis, Tattletale May, for her Secret Santa Gift!! But wait -- the Secret Santa gift is the perfect opportunity to give May exactly what she deserves...Maybe. Holiday fun with a lesson about giving is a perfect treat for the holiday season! OPAS Jr. Sponsored by OPAS Encore!, Chick-fil-A Aggieland and South College Station, and Blue Bell."),
array("JUNIE B. IN JINGLE BELLS, BATMAN SMELLS", "Sun Dec 8, 2013", "4:00 PM", "Sun Dec 8, 2013", "", "Rudder Theatre", "MSC OPAS", "junie_b350.jpg", "It's holiday time, and everyone's favorite first grader is back to celebrate! All of the students in Room One are happily creating the perfect holiday party. Except how is Junie B. supposed to enjoy anything when she has drawn the name of her arch nemesis, Tattletale May, for her Secret Santa Gift!! But wait -- the Secret Santa gift is the perfect opportunity to give May exactly what she deserves...Maybe. Holiday fun with a lesson about giving is a perfect treat for the holiday season! OPAS Jr. Sponsored by OPAS Encore!, Chick-fil-A Aggieland and South College Station, and Blue Bell."),
array("CHRISTMAS WITH THE BOSTON BRASS", "Tue Dec 10, 2013", "7:30 PM", "Tue Dec 10, 2013", "", "Rudder Theatre", "MSC OPAS", "bostonbrass350.jpg", "Hear all of your holiday favorites when these five humorous and talented guys perform a one-of-a-kind concert experience. \"White Christmas\" \"Frosty\" and \"The Christmas Song\" are just a few of the seasonal tunes you'll hear blowin' from two trumpets, a French horn, a trombone and a tuba! Series Sponsored by Sterling Auto Group, First Victoria, and Better Homes and Gardens Real Estate."),
array("Spring Poster Sale", "Mon Jan 13", "", "Fri Jan 17", "", "Rudder Plaza", "MSC Visual Arts Committee", "posterSALE.jpg", "The biannual MSC Poster Sale offers a wide range of full color and black and white posters with themes ranging from the visual arts, sports, and cinema, to music and nature. The poster sale is held during the first week of the new semester, just in time to help students fill in empty spots on their walls. MSC Visual Arts Committee, MSC Town Hall, and MSC Aggie Cinema will be selling posters from 10am until 5pm every day of the sale."),
array("Seventh Annual Rev. Dr. Martin Luther King, Jr. Breakfast ", "Thu Jan 16", "10:30 AM", "Thu Jan 16", "1:00 PM", "MSC 2300 (Ballroom)", "MSC Woodson Black Awareness Committee (WBAC)", "mlk_web.jpg", "The MLK Breakfast serves as a formal way to reflect on the life, legacy, and accomplishments of Dr. King. At Texas A&M, our hope is to not only honor King, but to also make his legacy relevant for the university and its students, faculty, and administration. We hope to utilize the passion and spirit associated with King, the Civil Rights Movement, and other leaders of the past to inspire and foster a spirit of action in the leaders of today and tomorrow. Tickets are available at the MSC Box Office."),
array("MSC Spring Open House", "Sun Jan 19", "2:00 PM", "Sun Jan 19", "5:00 PM", "Throughout the MSC", "MSC Marketing", "SPring-14-WEB2.jpg", "Are you looking for new opportunities to get involved in campus life? Want to join a professional organization? An academic, recreational, cultural, or social organization? Then you want to be at MSC Spring Open House. It's that simple. We'll have over 300 organizations present, so you can get some real \"face time\" with the involvement opportunities that interest you."),
array("MSC Abbott Family Leadership Conference", "Wed Jan 29", "3:00 PM", "Sun Feb 2", "3:00 PM", "San Antonio, TX", "MSC Abbott Family Leadership Conference", "alamo.jpg", "The purpose of the Abbott Family Leadership Conference is to help Aggie students put their lives on a rock solid foundation. The conferences are intended to help students establish their own value system that will allow them to positively face any life situation. The conference encourages delegates to set high standards for themselves so that they will be the master of their own destinies. Delegates are exposed to people and businesses that live and operate with strong moral, ethical, and community values. They experience firsthand the lives of those who have found the joy of giving and serving others. Walt Disney once said \"when your values are clear, decision making is much easier.\" For some, the conference will be the beginning of a lifelong quest for joyful living. The conference is not intended to offer a quick fix or a road map for problem-free living. Many of the outcomes of the conference will never be fully known to the Abbott family, the chairpersons and program directors, or the MSC staff. It may take years for the highly motivated student delegates and leaders to become fully aware of the value of their experiences during the conference. There already is much evidence that many lives have been enriched and impacted by a multitude of people that have crossed paths with each other and with the Abbott family. The conference seeks to challenge delegates to develop a holistic set of values that influence every aspect of their lives."),
array("Django Unchained", "Fri Jan 31", "7:00 PM", "Fri Jan 31", "10:00 PM", "MSC 2406A", "MSC Aggie Cinema", "djangounchained.jpg", "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner."),
array("Finding Nemo", "Fri Feb 7", "7:00 PM", "Fri Feb 7", "10:00 PM", "MSC 2406A", "MSC Aggie Cinema", "finding_nemo_wallpaper.jpg", "The wizards at Pixar take us under the sea to the world of clownfish Marlin and his son Nemo. When the defiant Nemo takes off from his dad and gets captured by a tropical fish seeker he finds himself stuck in a fishbowl in a dentist's office. Marlin and his well meaning, but wacky, friend Dory embark on an epic journey to find his son."),
array("PETER PAN", "Sun Feb 9", "2:00 PM", "Sun Feb 9", "", "Rudder Theatre", "MSC OPAS", "peterpan350.jpg", "Peter Pan is an adapted version of J.M. Barrie's classic tale created by John Caird and Trevor Nunn. This touring production explores the journey of a group of children in turn-of-the-century London who use their imaginations to reenact the story of Peter Pan. This story empowers children to create their own world of make-believe. As the children fly to Neverland and escape the evil Captain Hook and Mr. Smee, they recognize the importance of friendship as well as the value of being part of a family. This production encourages children to let their imaginations take \"flight\" and to create their own adventures using household objects as props and puppets as characters. Performance Sponsored by George Bush Presidential Library and Museum. OPAS Jr. Sponsored by OPAS Encore!, Chick-fil-A Aggieland and South College Station, and Blue Bell."),
array("Born into Brothels", "Tue Feb 11", "6:00 PM", "Tue Feb 11", "8:30 PM", "Hullabaloo", "MSC Aggie Cinema and MSC Freshman Leadership International", "born-into-brothels.jpg", "As part of Social Justice Week, MSC Aggie Cinema and MSC Fli present Born into Brothels: Calcutta's Red Light Kids. In the movie two documentary filmmakers chronicle their time in Sonagchi, Calcutta and the relationships they developed with children of prostitutes who work the city's notorious red light district."),
array("SCONA 59", "Thu Feb 20 ", "", "Sat Feb 22", "", "Throughout the MSC", "MSC Student Conference On National Affairs (SCONA)", "scona_web.jpg", "SCONA is an annual collegiate conference that brings delegates from all over the nation and the world. Each year, SCONA discusses a different topic of national importance, giving delegates the chance to interact with the nation's highest academic scholars, government officials, and well-known public figures. Delegates also participate in the debate through facilitated roundtables that culminate in a policy paper."),
array("The Impacts of Modern American Politics", "Tue Apr 1", "7:00 PM", "Tue Apr 1", "8:00 PM", "Rudder Auditorium", "MSC Wiley Lecture Series", "WileyLogo-Navy_Gold.png", "We hope you will join us for our main program of 2014, The Impacts of Modern American Politics, a discussion between two renowned experts: Dr. Condoleezza Rice, former US Secretary of State, and Dr. Douglas Brinkley, noted historian, author and professor at Rice University."),
);

$files = glob('images/160x103/*.{jpg,png,gif}', GLOB_BRACE);
foreach($files as &$file) {
	$file = basename($file);
}

foreach ($events as $eventindex => &$event) {
	foreach ($struct as $index => $field) {
		$event[$field] = $event[$index];
		unset($event[$index]);
	}
	// $event['Image'] = $files[$eventindex];
	// var_dump($files);
}
// Double the dummy events array to make more data (bc we have lots of images)
$cnt = count($events);
foreach ($events as $eventindex => $event) {
	$events[$eventindex + $cnt] = $event;
}
